CREATE DATABASE IF4101_Proyecto_B87581_B85042

USE IF4101_Proyecto_B87581_B85042

CREATE TABLE tb_Administradores(
	NAME_ADMIN VARCHAR(40) PRIMARY KEY
, PASSWORD_ADMIN VARCHAR(30) NOT NULL
)

INSERT INTO [tb_Administradores] (NAME_ADMIN,PASSWORD_ADMIN) VALUES('sysadmin','12345');

CREATE TABLE tb_Recintos(
  ID_RECINTO INT IDENTITY(1,1) PRIMARY KEY
, NAME_RECINTO VARCHAR(25) NOT NULL
)

INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Turrialba');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Paraíso');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Guápiles');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('San Ramón');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Grecia');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Liberia');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Santa Cruz');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Limón');
INSERT INTO tb_Recintos(NAME_RECINTO)VALUES('Golfito');

CREATE TABLE tb_Students(
 NAME_STUDENT VARCHAR(40) PRIMARY KEY
, PASSWORD VARCHAR(30) NOT NULL
, ID_RECINTO INT NOT NULL
, CONSTRAINT FK_ID_RECINTO FOREIGN KEY (ID_RECINTO) REFERENCES tb_Recintos(ID_RECINTO)
)

CREATE TABLE tb_Artists(
  ID_ARTIST INT IDENTITY(1,1) PRIMARY KEY
, FAMOUS_SONG VARCHAR(50) NOT NULL
, NAME_ARTIST VARCHAR(40) NOT NULL 
, PHOTO_ARTIST VARCHAR(80) NOT NULL 
)

CREATE TABLE tb_Events(
  ID_EVENT INT IDENTITY(1,1) PRIMARY KEY
, NAME_EVENT VARCHAR(40) NOT NULL
, ID_RECINTO INT NOT NULL
, TIME_START_EVENT DATETIME NOT NULL
, TIME_END_EVENT DATETIME NOT NULL
, TAQUILLA INT NOT NULL
, CONSTRAINT FK_ID_RECINTO FOREIGN KEY (ID_RECINTO) REFERENCES tb_Recintos(ID_RECINTO)
)

CREATE TABLE tb_Events_Artists(
  ID_EVENT INT NOT NULL
, ID_ARTIST INT NOT NULL
, CONSTRAINT FK_ID_EVENT FOREIGN KEY (ID_EVENT) REFERENCES tb_Events(ID_EVENT)
, CONSTRAINT FK_ID_ARTIST FOREIGN KEY (ID_ARTIST) REFERENCES tb_Artists(ID_ARTIST)
)

CREATE TABLE tb_Events_Students(
  ID_EVENT INT NOT NULL
, ID_STUDENTS INT NOT NULL
, CONSTRAINT FK_ID_EVENT FOREIGN KEY (ID_EVENT) REFERENCES tb_Events(ID_EVENT)
, CONSTRAINT FK_ID_STUDENTS FOREIGN KEY (ID_STUDENTS) REFERENCES tb_Students(ID_STUDENTS)
)

CREATE TABLE tb_Comment_Artist_Student(
  ID_ARTIST INT NOT NULL
, ID_STUDENT VARCHAR(7) NOT NULL
, COMMENT VARCHAR(300) NOT NULL 
, CONSTRAINT FK_ID_ARTIST_C FOREIGN KEY (ID_ARTIST) REFERENCES tb_Artists(ID_ARTIST)
, CONSTRAINT FK_ID_STUDENTS_C FOREIGN KEY (ID_STUDENT) REFERENCES tb_Students(ID)
)
